window.DZAtlasPageShell = (() => {
  const state = { items: [], query: "", category: "all", config: null };
  const normalize = value => String(value ?? "").toLowerCase().trim();
  const safe = value => String(value ?? "").replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  function initNavigation(){
    const sidebar=document.getElementById('primary-sidebar'), open=document.getElementById('mobile-menu-btn'), close=document.getElementById('mobile-menu-close'), backdrop=document.getElementById('mobile-drawer-backdrop');
    const set=v=>{sidebar?.classList.toggle('mobile-open',v);document.body.classList.toggle('mobile-drawer-active',v);open?.setAttribute('aria-expanded',String(v));};
    open?.addEventListener('click',()=>set(true));close?.addEventListener('click',()=>set(false));backdrop?.addEventListener('click',()=>set(false));
    document.addEventListener('keydown',e=>{if(e.key==='Escape')set(false)});sidebar?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>set(false)));
  }
  function iconFor(category=''){const c=normalize(category); if(c.includes('medical'))return'briefcase-medical';if(c.includes('military')||c.includes('armor'))return'shield-halved';if(c.includes('food'))return'utensils';if(c.includes('vehicle')||c.includes('car'))return'car';if(c.includes('weapon')||c.includes('rifle'))return'gun';if(c.includes('basic'))return'compass';if(c.includes('hostile'))return'skull';if(c.includes('friendly'))return'handshake';if(c.includes('event'))return'calendar-days';return'location-dot'}
  function getFiltered(){const {items,query,category,config}=state;return items.filter(item=>{const matchesCategory=category==='all'||normalize(config.category(item))===category;const hay=config.searchFields(item).map(normalize).join(' ');return matchesCategory&&(!query||hay.includes(query));});}
  function renderFilters(){const row=document.getElementById('category-filter-row');if(!row||!state.config)return;const cats=[...new Set(state.items.map(i=>state.config.category(i)).filter(Boolean))].sort();row.innerHTML=['all',...cats].map(c=>`<button type="button" class="category-filter-btn ${normalize(c)===state.category?'active':''}" data-category="${safe(normalize(c))}">${c==='all'?'All':safe(c)}</button>`).join('');row.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{state.category=b.dataset.category;renderFilters();render();}));}
  function render(){const container=document.getElementById(state.config.containerId), empty=document.getElementById('library-empty-state');if(!container)return;const rows=getFiltered();container.innerHTML=rows.map((item,index)=>state.config.card(item,index,safe,iconFor)).join('');document.getElementById('visible-result-count')?.replaceChildren(String(rows.length));document.getElementById('page-total-count')?.replaceChildren(String(state.items.length));empty?.classList.toggle('hidden',rows.length>0);container.classList.toggle('hidden',rows.length===0);}
  async function mount(config){state.config=config;const input=document.getElementById(config.searchId);try{const response=await fetch(config.dataFile);if(!response.ok)throw new Error(`HTTP ${response.status}`);state.items=await response.json();renderFilters();render();}catch(error){console.error(error);const empty=document.getElementById('library-empty-state');empty?.classList.remove('hidden');empty?.querySelector('h3')?.replaceChildren('Database unavailable');empty?.querySelector('p')?.replaceChildren('The data file could not be loaded. Check the file path and local server.');}
    input?.addEventListener('input',()=>{state.query=normalize(input.value);render();});document.querySelector('.search-clear-btn')?.addEventListener('click',()=>{if(input)input.value='';state.query='';render();input?.focus();});document.getElementById('reset-library-search')?.addEventListener('click',()=>{if(input)input.value='';state.query='';state.category='all';renderFilters();render();});
  }
  document.addEventListener('DOMContentLoaded',initNavigation);return{mount,safe,iconFor};
})();